import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navigation from './components/navigation';
import FAQ from './components/faq';
import Footer from './components/footer';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });
// const SHImogenAgnes = localFont({
//   src: './fonts/SH-Imogen-Agnes.ttf',
//   variable: '--font-script',
//   weight: '100 900',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-modern`}>
        <Navigation />
        {children}
        <FAQ />
        <Footer />
      </body>
    </html>
  );
}
