import '../globals.css';
import { SidebarProvider } from '@/components/shadcn/sidebar';
import type { Metadata } from 'next';
import { SideNavbar } from './components/layout/side-navbar';
import ThemeProvider from './components/theme/theme-provider';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Levia Admin',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/logo/logo-black.svg',
        href: '/logo/logo-black.svg',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/logo/logo-white.svg',
        href: '/logo/logo-white.svg',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialised">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <SideNavbar />
            <main className="w-full">{children}</main>
            <Toaster richColors />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
